---
title: "Mini-Project 2"
author: "Your Name Here"
date: "March 24, 2017"
output: html_document
---


## Loading the data


```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")

library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
```

```{r, message=FALSE, warning=FALSE}
candH <- candidates %>%
        filter(cand_office == "H", cand_office_state == "CA") %>%
        select(cand_id, cand_name, cand_party_affiliation, cand_election_yr)

names(house_elections)[names(house_elections) == "fec_id"] <- "cand_id"

elections <- house_elections %>%
            select(cand_id, general_votes, ge_winner)

contrib <- contributions %>%
          filter(transaction_type == "24E") %>%
          select(transaction_amt, cand_id)

table1 <- candH %>%
          full_join(elections, by = "cand_id") %>%
          filter(!is.na(ge_winner)) 

table2 <- table1 %>%
          full_join(contrib, by = "cand_id") %>%
          arrange(cand_name) %>%
          group_by(cand_name) %>%
          mutate(total_money = sum(transaction_amt),
                  total_votes = sum(general_votes)) %>%
          filter(cand_party_affiliation== "DEM" | cand_party_affiliation=="REP", !is.na(total_money))

plot1 <- ggplot(data=table2, aes(x=total_votes, y=total_money)) +
        geom_point(aes(colour=cand_party_affiliation, shape=ge_winner)) +
        geom_smooth(method = "lm") +
        ggtitle("Correlation between the number of votes and contributions \na candidate to the House elections received") +
        xlab("Number of Votes (millions)") +
        ylab("Amount of Contribution (millions of dollars)") +
        theme_economist() +
        scale_x_continuous(limits=c(0,15000000), breaks=c(0,10000000,15000000), labels = c("0","10","15")) +
       scale_y_continuous(limits=c(0,3200000), breaks=c(0,1000000, 2000000,3000000),labels=c("0","1","2", "3")) +
        scale_color_discrete(name = "party") +
        theme(legend.title = element_text(size = 11),
              legend.text = element_text(size = 9),
              legend.position = "right",
              axis.title = element_text(size = 11))
      
plot1



gen_el_table <- table2 %>%
  filter(cand_election_yr == "2012", general_votes > 0, cand_party_affiliation == "DEM" | cand_party_affiliation == "REP") %>%
  select(cand_id, cand_name, cand_party_affiliation, general_votes, ge_winner, transaction_amt) %>%
  group_by(cand_id, cand_name, cand_party_affiliation, general_votes, ge_winner) %>%
  summarize(total_money = sum(transaction_amt))


plot2 <- ggplot(data=gen_el_table, aes(x=general_votes, y=total_money)) +
  geom_point(aes(colour=cand_party_affiliation, shape=ge_winner)) +
  ggtitle("Number of Votes and Contributions \nin California General Election") +
  xlab("Number of Votes (in 100,000)") +
  ylab("Contribution to Candidate (in millions of dollars)") +
  theme_economist() +
  scale_x_continuous(limits=c(0, 300000), breaks=c(0, 150000, 300000), labels=c("0", "1.5", "3")) +
  scale_y_continuous(limits=c(0, 3200000), breaks=c(0, 1000000, 2000000, 3000000), labels=c("0", "1", "2", "3")) + scale_color_discrete(name = "party")

plot2

```

filter:
california
24E transactions: Independent expenditure advocating election of candidate
house elections
candidates from DEM and REP parties
